services:
  karakuri_agent:
    build: .
    container_name: "karakuri_agent"
    tty: true
    command: >
      /bin/sh -c "cd ~/workspace/karakuri_agent && flutter pub get &&  dart run rps run-release web"
    network_mode: "host"
    volumes:
      - ./:/home/ubuntu/workspace/karakuri_agent
    
