# Copyright (c) 0235 Inc.
# This file is licensed under the karakuri_agent Personal Use & No Warranty License.
# Please see the LICENSE file in the project root.

services:
  karakuri-agent-server:
    container_name: "karakuri-agent-server"
    volumes:
      - ./:/app
    build: 
      context: .
      dockerfile: .
    ports:
      - 8080:8080
