services:
  karakuri_agent:
    build: .
    container_name: "karakuri_agent"
    tty: true
    command: >
      /bin/sh -c "cd ~/workspace/karakuri_agent && 
      flutter clean && 
      flutter pub get && 
      flutter pub run build_runner build --delete-conflicting-outputs && 
      flutter run --release -d web-server --web-hostname=0.0.0.0 --web-port=50505"
    network_mode: "host"
    volumes:
      - ./:/home/ubuntu/workspace/karakuri_agent
    