name: karakuri_agent
description: "Karakuri agent."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.3
  flutter: "3.24.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_style: ^2.3.7
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/silero_models/
