name: karakuri_agent
description: "Karakuri agent."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.3
  flutter: "3.24.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  shared_preferences: ^2.3.2
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  js: ^0.7.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path: ^1.9.0
  sqflite: ^2.4.0
  sqflite_common_ffi_web: ^0.4.5+3
  http: ^1.2.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_style: ^2.3.7
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  slang_build_runner: ^3.31.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/silero_models/
