services:
  krakuri-agent-app-dev:
    build: .
    container_name: "krakuri-agent-app-dev"
    tty: true
    command: sleep infinity
    network_mode: "host"
    volumes:
      - ./:/home/ubuntu/workspace/karakuri_agent
