services:
  karakuri-agent-app-dev:
    build: .
    container_name: "karakuri-agent-app-dev"
    tty: true
    command: sleep infinity
    ports:
     - "50505:50505"
    volumes:
      - ./:/home/ubuntu/workspace/karakuri_agent
