name: check

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  FLUTTER_PATH: /home/ubuntu/flutter/bin

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/0235-jp/karkuri-agent-dev:latest
      options: --user root
    env:
      KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
      KEYSTORE_ALIAS_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_ALIAS_PASSWORD }}
      KEYSTORE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_STORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: /home/ubuntu/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-
      - uses: actions/cache@v3
        with:
          path: |
            /home/ubuntu/android-sdk/build-tools
            /home/ubuntu/android-sdk/platforms
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-android-sdk-
      - run: echo '${{ secrets.ENCODED_RELEASE_KEYSTORE }}' | base64 --decode > android/playstore.keystore
      - run: git config --global --add safe.directory /home/ubuntu/flutter
      - run: $FLUTTER_PATH/flutter pub get
      - run: $FLUTTER_PATH/flutter pub run build_runner build --delete-conflicting-outputs
      - run: $FLUTTER_PATH/flutter build apk --debug
      - uses: actions/upload-artifact@v3
        with:
          path: build/app/outputs/apk/release/app-release.apk
  build-web:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/0235-jp/karkuri-agent-dev:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: /home/ubuntu/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-
      - run: git config --global --add safe.directory /home/ubuntu/flutter
      - run: $FLUTTER_PATH/flutter pub get
      - run: $FLUTTER_PATH/flutter pub run build_runner build --delete-conflicting-outputs
      - run: $FLUTTER_PATH/flutter build web
      - uses: actions/upload-artifact@v3
        with:
          path: build/web
          retention-days: 1
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/0235-jp/karkuri-agent-dev:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory /home/ubuntu/flutter
      - run: $FLUTTER_PATH/flutter pub get
      - run: $FLUTTER_PATH/flutter pub run build_runner build --delete-conflicting-outputs
      - run: $FLUTTER_PATH/flutter test
